controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Recetas;
use yii\data\ActiveDataProvider;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
      public function actionRealfood()
    {
        return $this->render('realfood');
    }
    public function actionObjetivos()
    {
        return $this->render('objetivos');
    }
    
      public function actionAceite()
    {
        return $this->render('aceite');
    }
      public function actionLeche()
    {
        return $this->render('leche');
    }
      public function actionSetas()
    {
        return $this->render('setas');
    }
          public function actionTop3()
    {
        return $this->render('Top3');
    }
    
    public function actionRecetasporcategorias($id){
        $dataProvider = new ActiveDataProvider([
            'query' => Recetas::find()
                ->where("id_categorias=$id")
        ]);
        
        return $this->render("recetascategoria",[
            
            "dataProvider"=>$dataProvider,
        ]);
    }
    
    public function actionMostrarrecetas(){
       $dataProvider = new ActiveDataProvider([
           'query' => Recetas::find(),
           
       ]);
       
       return $this->render("recetas",[
       
       "dataProvider"=>$dataProvider,
       'titulo'=>'Nuestras Recetas',
       ]);
    }
}

views/site/Top3.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Top3';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <center><h1><?= Html::encode($this->title) ?></h1></center>
 <br></br>
     <div class="row">
            <div class="col-lg-12">

<br></br>
  <center><?= Html::img('@web/../img/Top1.png', ['alt' => '']) ?></center>
<br></br>
  <center><?= Html::img('@web/../img/Top4.png', ['alt' => '']) ?></center>
<br></br>
  <center><?= Html::img('@web/../img/Top2.png', ['alt' => '']) ?></center>
<br></br>

        </div>

</div>
<br></br>
 <div class="footer">
        <p>Footer</p>
    </div>
    
     <style>
  
        .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        }
        </style>
</div>

views/site/_recetas.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Nuestras recetas';

?>

<div class="col-sm-6n col-md12">
    <div class="thumbnail noticias" style=max-height:900px;">
        <div class="caption">
            
            <h2><?= $model->nombre ?></h2>
            
            <hr class="my-4">
                <h4>Características de la receta</h4>
            <div class="btn-group btn-group-justifieds" style=margin:10px;">
                <?= "Categoria de la receta: " . $model->categorias->nombre ?>
            </div>
            
            <div class="btn-group btn-group-justifieds" style=margin:10px;">
                <?= "Dificultad de la receta: " . $model->dificultad['dificultad'] ?>
             </div>
            
             <hr class="my-4">
             
                <h4>Ingredientes de la receta:</h4>
             <div>
                 <div style=margin-left:10px;display:inline-block;background:#E9E9E9;margin-bottom:4px;padding:4px;border-radius:5px;" ><?= implode('</div><div style=margin-left:10px;display:inline-block;background:#E9E9E9;margin-bottom:4px;padding:4px;border-radius:5px;">', ArrayHelper::getColumn($model->ingredientes, 'nombre')) ?></div>
             
                 <hr class="my-4">
                <h4>Pasos de la receta:</h4>
             <div>
                 <div style=margin-left:10px;display:inline-block;background:#E9E9E9;margin-bottom:4px;padding:4px;border-radius:5px;" ><?= implode('</div><div style=margin-left:10px;display:inline-block;background:#E9E9E9;margin-bottom:4px;padding:4px;border-radius:5px;">', ArrayHelper::getColumn($model->pasos, 'descripcion')) ?></div>
             
   </div>
    
  </div>
</div>
        </div>
<br></br>
     <div class="footer">
        <p>Footer</p>
    </div>
    
     <style>
  
        .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        }
        </style>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Sobre Nosotros y la tierruca';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <center><h1><?= Html::encode($this->title) ?></h1></center>

     <div class="row">
            <div class="col-lg-12">
                </br>
La gastronomía de nuestra tierra se ve beneficiada gracias a la situación geográfica tan privilegiada que presenta. Rodeada por el mar Cantábricos y las montañas de la cordillera Cántabra, cuenta con una amplia variedad de ingredientes.  

Los pescados y mariscos que nos ofrece el mar y los ríos, que riegan y bañan hasta llegar a su destino nuestros frondosos bosques y campos donde se encuentran las hortalizas y legumbres de la huerta, y los pastos de una ganadería autóctona.
                </br>
                </br>
El marisco es uno de los protagonistas en las mesas de nuestros restaurantes y casas. Gracias a las frías y limpias aguas de las que procede posee una gran diversidad y calidad. Si bien puede conseguirse en toda la costa, es en la bahía de Santander donde se encuentran los mejores ejemplares. 

El vacuno es la carne cántabra por excelencia, donde destaca la de la vaca tudanca. No hay que olvidar que la feria ganadera más importante de España, la Feria Nacional de Ganados de Torrelavega, se celebra en esta región.

La caza también ofrece carne de gran calidad: venado, corzo y jabalí. El chon es un elemento clave para el cocido montañés, al que además se le añaden alubias, berzas, chorizo y morcilla de arroz.
               <br></br>
  <center><?= Html::img('@web/../img/cantabria1.png', ['alt' => '']) ?></center>
 <br></br>
Es indiscutible la excelencia de la leche cántabra, por lo que no puede extrañar que los derivados de la misma proliferen por toda la región: la mantequilla, el queso de nata, que puede encontrarse por toda la región; el queso picón en Tresviso y Bejes; quesos ahumados como los de Áliva o Pido; o los pequeños quesucos, realizados con la mezcla de leche de vaca y oveja. 

Además, de todos los productos derivados, que permiten realizar una repostería como los tradicionales sobaos y quesadas pasiegas. También es muy típico el hojaldre, que según la zona adopta diferentes nombres siendo de igual manera de una excelente calidad.

Por otro lado, la Miel de Liébana es una denominación de origen protegida (DOP) de miel propia de la comarca de Liébana.
                <br></br>
  <center><?= Html::img('@web/../img/cantabria2.png', ['alt' => '']) ?></center>
 <br></br>
La bebida más característica de esta región es el orujo, elaborado artesanalmente, y destilado gota a gota. Dicen los entendidos que el orujo es una bebida excelente para aliviar digestiones pesadas. Históricamente hubo gran producción de sidra y chacolí, que tras un importante declive se está recuperando en los últimos años. Cantabria cuenta actualmente con dos certificaciones de origen en vinos: Vino de la Tierra Costa de Cantabria y Vino de la Tierra de Liébana. 

            </div>
        </div>

</div>
</br>
    </br>

 <div class="footer">
        <p>Footer</p>
    </div>
    
     <style>
  
        .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        }
        </style>
</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */

$this->title = 'Las Recetucas';

?>

<div class="site-index">
    
     <?= Html::a(Html::img('@web/../img/ig.png'),Url::to('https://www.instagram.com/lasrecetucas', true))?>

    <div class="jumbotron">
   
      <center><?= Html::img('@web/../img/logorecetucas.png', ['alt' => '']) ?></center>
      
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <center><h2>Nuestro Nombre</h2></center>

                <p>Buscando utilizar la terminación "-uco" para denotar nuestros origenes y darle al nombre una connotación más entrañable y cariñosa. La gastronomía de nuestra tierra se ve beneficiada gracias a la situación geográfica tan privilegiada que presenta.</p>

                <center><p><a class="btn btn-default" href="@web/../index.php/site/about">Conoce más</a></p></center>
            </div>
            <div class="col-lg-4">
                <center><h2>Objetivos</h2></center>

                <p>De clara vocación tradicional, las recetucas es ante todo una página web abierta, moderna y dinámica, un espacio para crear, desarrollar y compartir nuevas tendencias y conocimientos que aporten un valor añadido al sector culinario.</p>

                <center><p><a class="btn btn-default" href="@web/../index.php/site/objetivos">Objetivos</a></p></center>
            </div>
            <div class="col-lg-4">
                <center><h2>Real Food</h2></center>

                <p>La alimentación se ha centrado en nutrientes y calorías, en lugar de alimentos, en lugar de comida real. Hablamos en términos de hidratos de carbono, grasas, proteínas, vitaminas, minerales… cuando todo eso no tiene nada que ver con la salud.</p>

                <center><p><a class="btn btn-default" href="@web/../index.php/site/realfood">Real Food</a></p></center>
            </div>
        </div>
        </br></br>
      <center><?= Html::a(Html::img('@web/../img/top3.png', ['alt' => 'Top3']),['site/top3'])?></center>
             
        
  </div><div class="body-content">
    <div class= "jumbotron">
    <h2><b>Recetas por Categorías<b/></h2>
    </div>
  <div class="d-flex justify-content-center">
   <div class="row">
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/postres.png', ['alt' => '']) ?></center>
        </br>
          <center><?= Html::a('Postres', ['site/recetasporcategorias','id' => 1], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="/index.php/site/recetasporcategoria" class="btn btn-default" role="button">Postres</a></p></center>-->
        </div>
    </div>
       
    
     <div class="col-sm-3">
        <div class="thumbnail">
       <center><?= Html::img('@web/../img/arroces.png', ['alt' => '']) ?></center>
        </br>
          <center><?= Html::a('Arroces', ['site/recetasporcategorias','id' => 2], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Arroces</a></p></center>-->
        </div>
    </div>
  
   
     <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/picoteo.png', ['alt' => '']) ?></center>
        </br>
           <center><?= Html::a('Picoteo', ['site/recetasporcategorias','id' => 3], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Picoteo</a></p></center>-->
        </div>
    </div>
             
    
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/carnes.png', ['alt' => '']) ?></center>
        </br>
           <center><?= Html::a('Carnes', ['site/recetasporcategorias','id' => 4], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Carnes</a></p></center>-->
        </div>
    </div>
    
     <div class="row">
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/cremas.png', ['alt' => '']) ?></center>
        </br>
          <center><?= Html::a('Cremas', ['site/recetasporcategorias','id' => 5], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Cremas y Sopas</a></p></center>-->
        </div>
    </div>
       
    
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/ensaladas.png', ['alt' => '']) ?></center>
        </br>
          <center><?= Html::a('Ensaladas', ['site/recetasporcategorias','id' => 6], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Ensaladas</a></p></center>-->
        </div>
    </div>
  
    
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/huevos.png', ['alt' => '']) ?></center>
        </br>
          <center><?= Html::a('Huevos', ['site/recetasporcategorias','id' => 7], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Huevos</a></p></center>-->
        </div>
    </div>
             
    
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/pizzas.png', ['alt' => '']) ?></center>
        </br>
        <center><?= Html::a('Pasta y Pizzas', ['site/recetasporcategorias','id' => 8], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Pizzas</a></p></center>-->
        </div>
    </div>
    
      <div class="row">
    <div class="col-sm-3">
        <div class="thumbnail">
       <center><?= Html::img('@web/../img/pescados.png', ['alt' => '']) ?></center>
        </br>
        <center><?= Html::a('Pescados', ['site/recetasporcategorias','id' => 9], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Pescados y Mariscos</a></p></center>-->
        </div>
    </div>
       
   
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/potajes.png', ['alt' => '']) ?></center>
        </br>
        <center><?= Html::a('Potajes', ['site/recetasporcategorias','id' => 10], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Potajes y Legumbres</a></p></center>-->
        </div>
    </div>
  
    
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/setas.png', ['alt' => '']) ?></center>
        </br>
        <center><?= Html::a('Setas', ['site/recetasporcategorias','id' => 11], ['class' => 'btn btn-default']) ?></center>
<!--       <center><p><a href="#" class="btn btn-default" role="button">Setas y Hongos</a></p></center>-->
        </div>
    </div>
             
   
    <div class="col-sm-3">
        <div class="thumbnail">
        <center><?= Html::img('@web/../img/verduras.png', ['alt' => '']) ?></center>
        </br>
        <center><?= Html::a('Verduras', ['site/recetasporcategorias','id' => 12], ['class' => 'btn btn-default']) ?></center>
        
<!--       <center><p><a href="#" class="btn btn-default" role="button">Verduras y Hortalizas</a></p></center>-->
        </div>
                <br>
        </br>

    </div>
          
<div class="col-sm-1">
         <center><?= Html::a(Html::img('@web/../img/promo1.png', ['alt' => '']),['site/mostrarrecetas'])?></center>
</div>
           </div><div class="body-content">
    <div class= "jumbotron">
    <h2><b>Noticias de Actualidad<b/></h2>
    </div>
      
  <center><?= Html::img('@web/../img/aceite1.png', ['alt' => '']) ?></center>
 <br></br>
                <h4>El aceite de oliva, conoce los beneficios del oro líquido.
                Es la piedra angular de la Dieta Mediterránea, el aceite no sólo destaca por sus
cualidades organolépticas, sino que, además, tiene multitud de ventajas para
nuestra salud. Conoce sus tipos y cómo sacarle el máximo partido en la cocina.</h4>

                <center><?= Html::a('Recetas con Aceite de Oliva', ['recetas/recetasporingrediente','ingrediente' => 8], ['class' => 'btn btn-default']) ?></center>

 <br></br>
  <center><?= Html::img('@web/../img/leche.jpg', ['alt' => '']) ?></center>
 <br></br>
                <h4>Esencial en todas las fases de la vida: la leche hace bien a nuestra salud. La
OMS (Organización Mundial de la Salud) recomienda tres porciones diarias de
leche o derivados como el yogurt, el queso o las bebidas derivadas de la leche.</h4>

                <center><?= Html::a('Recetas con Leche', ['recetas/recetasporingrediente','ingrediente' => 10], ['class' => 'btn btn-default']) ?></center>
                
 
 <br></br>
  <center><?= Html::img('@web/../img/setas1.png', ['alt' => '']) ?></center>
 <br></br>
                <h4>Más allá de ser ingrediente de algunos de los platos más nobles, las setas
tienen un alto valor nutricional y para la salud por las distinas sustancias y
componentes que aportan y por los efectos que tienen sobre nuestro
metabolismo.</h4>

                <center><?= Html::a('Recetas con Setas', ['recetas/recetasporingrediente','ingrediente' => 17], ['class' => 'btn btn-default']) ?></center>
            </div>
    
    <div class="footer">
        <p>Footer</p>
    </div>
    
     <style>
  
        .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        }
        </style>
</div>

views/site/leche.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = ''
        . 'Leche';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <center><h1><?= Html::encode($this->title) ?></h1></center>
    <br></br>
  <center><?= Html::img('@web/../img/cantabria.png', ['alt' => '']) ?></center>
   <br></br>
     <div class="row">
            <div class="col-lg-12">
A muchas personas les cuesta beber leche en la etapa adulta ya sea porque no les gusta el sabor o por intolerancia a la lactosa. Sin embargo, también existen personas que no lo hacen porque creen que la leche es mala para los adultos.

Existen varios mitos sobre la producción, distribución y efectos de la leche en el organismo que merecen ser aclarados.

Esencial en todas las fases de la vida: la leche hace bien a nuestra salud. La OMS (Organización Mundial de la Salud) recomienda tres porciones diarias de leche o derivados como el yogurt, el queso o las bebidas derivadas de la leche.

Alimento completo: la leche es un alimento completo, fuente de diferentes nutrientes esenciales como las proteínas, los minerales (fósforo y zinc) y calcio. También es responsable de la salud ósea.

Bueno para dormir: la leche también te puede ayudar a dormir. De hecho, el calcio estimula la relajación y el aminoácido triptófano aumenta la cantidad de serotonina en el cerebro, vital para el sueño.
<br></br>
<center><?= Html::img('@web/../img/leche1.png', ['alt' => '']) ?></center>
       <br></br>
Recomendada para actividades físicas: poca gente lo sabe pero la leche es una gran bebida hidratante. Consumirla tras hacer ejercicio beneficia a los músculos y a la hidratación.

Prevención del cáncer: ¿Quieres otro motivo para beber leche? diversos estudios apuntan a que la leche y sus nutrientes (como el calcio, la vitamina D, la lactoferrina y las proteínas del suero de leche) tienen efectos positivos sobre la reducción de posibilidad de contraer cáncer, especialmente el de colon.

Aumenta la inmunidad: este alimento es poderoso para aislarte de las enfermedades, además posee una gran acción antioxidante.


<br></br>
          <center><?= Html::a('Recetas con Leche', ['site/recetasporcategorias','id' => 7], ['class' => 'btn btn-default']) ?></center>
            </div>

</div>
<br></br>
     <div class="footer">
        <p>Footer</p>
    </div>
    
     <style>
  
        .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        }
        </style>
</div>

views/site/setas.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Setas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <center><h1><?= Html::encode($this->title) ?></h1></center>
    <br></br>
  <center><?= Html::img('@web/../img/setas1.png', ['alt' => '']) ?></center>
   <br></br>
     <div class="row">
            <div class="col-lg-12">
La temporada de setas se estrena en los bosques de media España con la recogida de las principales especies, que verán su valor aumentado en las verdulerías dada su condición de exquisitez gastronómica, muy apreciada en algunas zonas del país. 

Pero más allá de ser ingrediente de algunos de los platos más nobles, las setas tienen un alto valor nutricional y para la salud por las distinas sustancias y componentes que aportan y por los efectos que tienen sobre nuestro metabolismo. A continuación te reportamos diez beneficios de comer setas, si bien los mismos se dan más en el consumo de las setas salvajes que en las cultivadas industrialmente. 
<br></br>
1. Aportan fibra insoluble
En efecto, la lignina es uno de los principales ingredientes de las setas, con 2,5 gramos por cada 100 gramos, donde la mayor parte es agua. Se trata de una fibra leñosa, de relativo valor biológico de cara a la microbiota pero muy buena como fibra de arrastre para limpiar el tracto intestinal y también por su capacidad de hinchar se y dar consistencia al bolo. Para saber más te recomendamos: Ocho razones para reintroducir en nuestra dieta la fibra insoluble.
<br></br>
2. Tienen un alto poder saciante
Precisamente esta capacidad de la lignina de retener agua e hincharse en el estómago, aumenta la sensación de estómago lleno tras la ingesta de setas y hace que no queramos comer tanto, que seamos mas frugales y controlemos así la ingesta calórica previniendo la obesidad. Sobre el poder saciante te recomendamos: Siete alimentos para vigilar el peso sin recurrir a dietas milagro.
<br></br>
3. Contienen elementos antioxidantes
Un estudio de 2007 publicado en Journal of Nutrition destacaba el papel del aminoácido ergoteína, presente en la proteína de las setas, como un potente antioxidante con gran presencia en el champiñón silvestre, aunque no tanto en el industrial. El estudio destacaba además que dicho papel le confería un interesante papel preventivo ante distintos tipos de tumores. 
<br></br>
4. Tienen un bajo poder calórico
Como ya se ha explicado, su mayor porcentaje es agua y apenas suman 4 gramos por cada 100 de hidratos de carbono. Su poder calórico son 25 Kcal, lo que las hace un perfecto acompañamiento para todo tipo de platos o incluso solas, cuando hemos superado la ingesta diaria recomendada calórica pero tenemos hambre.
  <br></br>
  <center><?= Html::img('@web/../img/setas2.png', ['alt' => '']) ?></center>
   <br></br>
5. Aportan vitaminas y minerales imprescindibles
Según la Fundación Española del Corazón, que las recomienda como pieza clave en la lucha contra las enfermedades cardiovasculares, las setas son ricas en hierro, fósforo, yodo, magnesio, selenio, calcio, potasio, zinc, además de vitamina A y vitaminas del grupo B (concretamente B1, B2, B3), así como C y vitamina D que autosintetiza con la luz solar, al igual que los humanos. Aunque su versión, la D3, parece no ser tan eficaz como la D2, si puede ayudar. Destaca también por su bajo aporte en sodio, por lo que tiene incidencia positiva sobre la presión arterial, aunque esta desaparece al salarlas.
<br></br>
6. Pueden aportar los aminoácidos esenciales
Al ser una vía evolutiva intermedia entre los vegetales y los animales, su proteína está más cercana a la de estos últimos, la nuestra, y por lo tanto se considera de superior valor biológico, ya que en algunos géneros como es el caso de Pleurotus sp (el de la seta de ostra), se pueden encontrar todos los aminoácidos esenciales, según un estudio. 
<br></br>
7. Pueden ser un sustituto de la carne
Tanto por su proteína, que aunque no es muy abundante es de alta calidad, como por su contenido en aminoácidos esenciales, y también por su sabor umami, las setas pueden ayudarnos a reducir la ingesta semanal de carne roja. Te recomendamos el artículo Alimentos que nos pueden ayudar a decir adiós a la carne.
<br></br>
8. Pueden mejorar la diversidad de la microbiota
Hay varios estudios (este y este) que avalan que la lignina de las setas puede ayudar a mejorar la diversidad de la flora intestinal favoreciendo a ciertas bacterias que intervendrían en la reducción de la obesidad.
<br></br>
9. Aportan compuestos antiinflamatorios
Algunos de los hidratos de carbono de ciertas setas son ricos en betaglucanos, un polisacárido al que esta revisión le otorga grandes beneficios como antiinflamatorio y desarrollador del sistema inmunitario. Esta publicación también incide en el mismo sentido.
<br></br>
10. Ayudan a reducir el colesterol malo
Algunas setas son ricas en ácido linolénico conjugado, un ácido graso omega-6 que ayuda a reducir el colesterol metabólico malo o LDL. Además, sus cantidades son moderadas en relación a los suplementos de este ácido, que se han calificado de peligrosos tras algunos estudios en ratones.

     <br></br>
<center><?= Html::img('@web/../img/setas3.png', ['alt' => '']) ?></center>
       <br></br>
       
       <center><?= Html::a('Recetas con Setas', ['site/recetasporcategorias','id' => 7], ['class' => 'btn btn-default']) ?></center>
       
            </div>
     

          
    
</div>
<br></br>
     <div class="footer">
        <p>Footer</p>
    </div>
    
     <style>
  
        .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        }
        </style>
</div>